from yoyo import step

steps = [
    step(
        """
        create table if not exists zno_data (
            OUTID varchar(500) PRIMARY KEY NOT NULL,
            Birth integer NOT NULL,
            SexTypeName varchar(500) NOT NULL,
            RegName varchar(500) NOT NULL,
            AREANAME varchar(500) NOT NULL,
            TERNAME varchar(500) NOT NULL,
            RegTypeName varchar(500) NOT NULL,
            TerTypeName varchar(500) NOT NULL,
            ClassProfileNAME varchar(500),
            ClassLangName varchar(500),
            EONAME varchar(500),
            EOTypeName varchar(500),
            EORegName varchar(500),
            EOAreaName varchar(500),
            EOTerName varchar(500),
            EOParent varchar(500),
            UMLTest varchar(500),
            UMLTestStatus varchar(500),
            UMLBall100 numeric(4,1),
            UMLBall12 integer,
            UMLBall numeric(4,1),
            UMLAdaptScale varchar(500),
            UMLPTName varchar(500),
            UMLPTRegName varchar(500),
            UMLPTAreaName varchar(500),
            UMLPTTerName varchar(500),
            UkrTest varchar(500),
            UkrSubTest varchar(500),
            UkrTestStatus varchar(500),
            UkrBall100 numeric(4,1),
            UkrBall12 integer,
            UkrBall numeric(4,1),
            UkrAdaptScale varchar(500),
            UkrPTName varchar(500),
            UkrPTRegName varchar(500),
            UkrPTAreaName varchar(500),
            UkrPTTerName varchar(500),
            HistTest varchar(500),
            HistLang varchar(500),
            HistTestStatus varchar(500),
            HistBall100 varchar(500),
            HistBall12 varchar(500),
            HistBall varchar(500),
            HistPTName varchar(500),
            HistPTRegName varchar(500),
            HistPTAreaName varchar(500),
            HistPTTerName varchar(500),
            MathTest varchar(500),
            MathLang varchar(500),
            MathTestStatus varchar(500),
            MathBall100 numeric(4,1),
            MathBall12 integer,
            MathDpaLevel varchar(500),
            MathBall numeric(4,1),
            MathPTName varchar(500),
            MathPTRegName varchar(500),
            MathPTAreaName varchar(500),
            MathPTTerName varchar(500),
            MathStTest varchar(500),
            MathStLang varchar(500),
            MathStTestStatus varchar(500),
            MathStBall12 varchar(500),
            MathStBall varchar(500),
            MathStPTName varchar(500),
            MathStPTRegName varchar(500),
            MathStPTAreaName varchar(500),
            MathStPTTerName varchar(500),
            PhysTest varchar(500),
            PhysLang varchar(500),
            PhysTestStatus varchar(500),
            PhysBall100 numeric(4,1),
            PhysBall12 integer,
            PhysBall numeric(4,1),
            PhysPTName varchar(500),
            PhysPTRegName varchar(500),
            PhysPTAreaName varchar(500),
            PhysPTTerName varchar(500),
            ChemTest varchar(500),
            ChemLang varchar(500),
            ChemTestStatus varchar(500),
            ChemBall100 numeric(4,1),
            ChemBall12 integer,
            ChemBall numeric(4,1),
            ChemPTName varchar(500),
            ChemPTRegName varchar(500),
            ChemPTAreaName varchar(500),
            ChemPTTerName varchar(500),
            BioTest varchar(500),
            BioLang varchar(500),
            BioTestStatus varchar(500),
            BioBall100 numeric(4,1),
            BioBall12 integer,
            BioBall numeric(4,1),
            BioPTName varchar(500),
            BioPTRegName varchar(500),
            BioPTAreaName varchar(500),
            BioPTTerName varchar(500),
            GeoTest varchar(500),
            GeoLang varchar(500),
            GeoTestStatus varchar(500),
            GeoBall100 numeric(4,1),
            GeoBall12 integer,
            GeoBall numeric(4,1),
            GeoPTName varchar(500),
            GeoPTRegName varchar(500),
            GeoPTAreaName varchar(500),
            GeoPTTerName varchar(500),
            EngTest varchar(500),
            EngTestStatus varchar(500),
            EngBall100 numeric(4,1),
            EngBall12 integer,
            EngDPALevel varchar(500),
            EngBall numeric(4,1),
            EngPTName varchar(500),
            EngPTRegName varchar(500),
            EngPTAreaName varchar(500),
            EngPTTerName varchar(500),
            FraTest varchar(500),
            FraTestStatus varchar(500),
            FraBall100 numeric(4,1),
            FraBall12 integer,
            FraDPALevel varchar(500),
            FraBall numeric(4,1),
            FraPTName varchar(500),
            FraPTRegName varchar(500),
            FraPTAreaName varchar(500),
            FraPTTerName varchar(500),
            DeuTest varchar(500),
            DeuTestStatus varchar(500),
            DeuBall100 numeric(4,1),
            DeuBall12 integer,
            DeuDPALevel varchar(500),
            DeuBall numeric(4,1),
            DeuPTName varchar(500),
            DeuPTRegName varchar(500),
            DeuPTAreaName varchar(500),
            DeuPTTerName varchar(500),
            SpaTest varchar(500),
            SpaTestStatus varchar(500),
            SpaBall100 numeric(4,1),
            SpaBall12 integer,
            SpaDPALevel varchar(500),
            SpaBall numeric(4,1),
            SpaPTName varchar(500),
            SpaPTRegName varchar(500),
            SpaPTAreaName varchar(500),
            SpaPTTerName varchar(500),
            HisBall12 integer,
            HisBall100 numeric(4,1),
            HisBall numeric(4,1),
            year integer
        );
        """
    )
]
